### PR TITLE
Add support for scoping to multiple tenants.

### PR DESCRIPTION
**Pull request by inkadnb**
This is useful for tenant hierarchy scenarios as well as administration.

### CODE REVIEW

**Comment by HipsterJazzbo** [comment]
Can you give an example of where you'd use this?

**Comment by inkadnb** [comment]
@HipsterJazzbo sure, this is useful in hierarchical tenancy scenarios. I.e. something like:

Tenant A is parent to Tenant B and Tenant C, therefore a user on Tenant A could see data on Tenant A, B, and C. Whereas a user on Tenant B may see data on Tenant A and Tenant B but not Tenant C.

In a real-world situation Tenant A could be "Corporate" and Tenant B and C could be "Franchisees"

**Comment by HipsterJazzbo** [comment]
Are all those tenants from the same table?

**Comment by inkadnb** [comment]
@HipsterJazzbo yes they are.

**Comment by HipsterJazzbo** [comment]
Hmm I see what you're doing there. However, this library is specifically targeted at doing everything it can to only have ONE of a given tenant registered at any one time, for purposes of data siloing. I think this is outside the scope of this library.

You should be able to whip up your own global scope to handle that situation quite easily though.

**Pull request closed without merging**
