### PR TITLE
Fix compatibility with parent class

### PR DESCRIPTION
**Pull request by jscrobinson**
Fix for https://github.com/HipsterJazzbo/Landlord/issues/39

### CODE REVIEW

**Comment by torkiljohnsen** [comment]
Your code is only compatible with >= 5.3.19. 

Check out #42, where I fixed the same issue, but in a way that is compatible with all of 5.3.*.

**Comment by jimrobinson-croud** [comment]
Thanks @torkiljohnsen, I'd forgotten to pass the $ids parameter to the parent method.

**Comment by torkiljohnsen** [comment]
@jimrobinson-croud Actually, no: By passing the `$ids` parameter to the parent method, your code will only work with Laravel >= 5.3.19.

By **not** passing the `$ids` parameter, the code will work with all Laravel 5.3 versions.

**Comment by torkiljohnsen** [comment]
Actually, `parent::setModel($model)` could just be replaced with `$this->model = $model;`. Less overhead.

**Comment by jscrobinson** [comment]
Good point. Thanks again @torkiljohnsen

**Pull request closed without merging**
