### PR TITLE
Updated compatibility to Laravel 5.5

### PR DESCRIPTION
**Pull request by rikvdlooi**
Walked trough the [upgrade guide](https://laravel.com/docs/5.5/upgrade), no changes had to be made to the code according to the guide.

### CODE REVIEW

**Comment by buraksh** [comment]
Could you add package auto-discovery support as well?

**Comment by rikvdlooi** [comment]
Good Idea, didn't think about that. I will update the PR tomorrow as I don't have the time now.

**Comment by rikvdlooi** [comment]
Tested with a personal project and the package auto-discovery works :smile:

**Comment by divdax** [comment]
Maybe the README also should get an update? (auto-discovery) 😄

**Comment by rikvdlooi** [comment]
Yeah, but I don't know if @HipsterJazzbo wants to do it himself or if it should be included with the PR.

**Comment by rikvdlooi** [comment]
Now really fixed the auto-discovery. The facade wasn't correctly implemented before.

**Comment by chrisgillis** [comment]
Looking forward to this.

**Comment by setefocos** [comment]
Pleeeeease!! =)

**Comment by HipsterJazzbo** [comment]
Looks good :)

**Pull request merged**
